Algoritmo "Atividade 3"

Var
p1,p2: caractere
I1,I2,mut: inteiro

Inicio
      escreval ("Informe seu nome é idade respectivamente:")
leia (p1)
leia (I1)
     escreval ("Escreva outro none é idade respectivamente:")
leia (p2)
leia (I2)
 mut <- (I1*I2)
     escreval ("A mutiplicação das idades de ",p1," é ",p2," é igual a",mut)

Fimalgoritmo

//Nome: WESLEY HENRIQUE DA SILVA CRUZ
//Matricula: 19262140