Algoritmo "Atividade 5"

Var
a,b,qoo,res: real

Inicio
      escreval ("informe o valor do dividendo:")
leia (a)
      escreval ("agora informe o valor do divisor: ")
leia (b)
  qoo <- (a/b)
  res <- (a mod b)
      escreval ("o dividendo é",a)
      escreval ("o divisor é",b)
      escreval ("o quosiente da divisçao é",qoo)
      escreval ("o resto da diviçao é",res)
      
      
Fimalgoritmo

//Nome: WESLEY HENRIQUE DA SILVA CRUZ
//Matricula: 19262140