Algoritmo "Atividade 1"

Var
P1,P2,P3,P4,P5,Med:real

Inicio
      escreval ("informe respectivamente suas notas:")
leia (p1)
leia (p2)
leia (p3)
leia (p4)
leia (p5)
 Med <- ((P1+P2+P3+P4+P5)/5)
     escreval("Amedia final do aluno é ",Med)
se (Med>7)entao
     escreval("aluno Aprovado")
senao
     escreval("aluno REPROVADO")
fimse

Fimalgoritmo

//Nome: WESLEY HENRIQUE DA SILVA CRUZ
//Matricula: 19262140