Algoritmo "Atividade 8"

Var
C1,J1,M1,F1: real


Inicio
      escreval ("informe o valor do capital arecadado: ")
leia (C1)
      ESCREVAL ("informe o valor do juros mensal fixo: ")
leia (J1)
      escreval ("informe a quantidades de meses percorido: ")
leia (M1)
  F1 <- C1*(1+J1/100)*M1
escreval ("o valor arecadado no final do periodo foi",F1)


Fimalgoritmo

//Nome: WESLEY HENRIQUE DA SILVA CRUZ
//Matricula: 19262140