Algoritmo "Atividade 4"

Var
n1,qua,tri,rais,soma: real

Inicio
      escreval ("ecreva um numero inteiro:")
leia (n1)
  qua <- n1^2
  tri <- n1^3
  rais <- raizq(n1)
  soma <- qua+tri
      escreval ("o quatrado de ",n1," é igual a ",qua)
      escreval ("o triplo de ",n1," é igual a ",tri)
      escreval ("a raiz de ",n1," é igual a ",rais)
      escreval ("a soma do quatrado pelo triplo de ",n1," é igual a ",soma)

Fimalgoritmo

//Nome: WESLEY HENRIQUE DA SILVA CRUZ
//Matricula: 19262140