Algoritmo "Atividade 10"

Var
anonas,anoatu,ida: inteiro

Inicio
      escreval ("qual é o ano do seu nascimento: ")
leia (anonas)
      escreval ("informe o ano atual : ")
leia (anoatu)
  ida <- anoatu-anonas
      escreval ("sua idade atual é ",ida)
      escreval ("sua idade em meses é ",(ida*12))
      escreval ("sua idade em 2050 sera ",(2050-anonas))

Fimalgoritmo

//Nome: WESLEY HENRIQUE DA SILVA CRUZ
//Matricula: 19262140