Algoritmo "Atividade 13 "

Var
ida: inteiro

Inicio

      escreval ("qual a sua idade?")
leia (ida)
se (ida>=18)entao
      escreval ("voce é maior de idade!")
      senao
      escreval ("voce NAO é maior de idade!")
fimse
se (ida>=65)entao
      escreval ("e voce é um IDOSO!")
      senao
      escreval ("e voce NAO é um idoso!")
fimse

Fimalgoritmo

//Nome: WESLEY HENRIQUE DA SILVA CRUZ
//Matricula: 19262140
