Algoritmo "Atividade 11"

Var
n1,n2: inteiro

Inicio
leia (n1)
leia (n2)
se (n1=n2) entao
   escreval ("são iguais!")
senao
se (n1>n2) entao
   escreval ("a raiz do maior numero é:",raizq(n1))
   escreval ("o quadrado do menor numero é:",(n2^2))
senao
   escreval ("o quadrado do menor numero é:",(n1^2))
   escreval ("a raiz do maior numero é:",raizq(n2))
fimse
fimse


Fimalgoritmo

//Nome: WESLEY HENRIQUE DA SILVA CRUZ
//Matricula: 19262140