Algoritmo "Atividade 2"

Var
N1,ant,sus,sub,mut: inteiro

Inicio
      ESCREVAL ("Escolha um numero inteiro: ")
leia (N1)
 ant <- (N1-1)
 sus <- (N1+1)
 sub <- (N1-ant)
 mut <- (N1*sus)
     ESCREVAL ("A subtração com o antecessor de",N1," é igual a",sub)
     ESCREVAL ("A mutiplicação com o sucessor de",N1," é iagual a",mut)

Fimalgoritmo

//Nome: WESLEY HENRIQUE DA SILVA CRUZ
//Matricula: 19262140